### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by SuAnita520** [gengyanlei/reflective-clothes-detect#3]
My OS: Ubuntu
Python: 3.7 
Issue:
I came across "ValueError: invalid literal for int() with base 10: '' when I ran "train.py".
Above error happened in folder "utils" > general.py around line 956 -ish...
Solution:
```
update_NUM = 0
for x in d:
    if '_' in x:
        tmp_NUM = int(x[len(dir):])
        if tmp_NUM > update_NUM:
            update_NUM = tmp_NUM
n = update_NUM + 1
# n = max([int(x[len(dir):x.find('_') if '_' in x else None]) for x in d]) + 1  # increment
```
The actual error is at "int(x[len(dir):x.find('_') if '_' in x else None])", I solved it via changing "in-line" code to several lines.
Please correct me if I got any inappropriate

**Comment by gengyanlei** [comment]
@Remosy 
tks
